export const contentTypes = [
  "music",
  "songs",
  "podcasts",
  "audio_tracks",
  "digital_art",
  "paintings",
  "photography",
  "ui_ux_design",
  "graphic_design",
  "3d_models",
  "animations",
  "films",
  "short_movies",
  "cinematic_edits",
  "documentaries",
  "books",
  "stories",
  "poetry",
  "articles",
  "blogs",
  "coding_projects",
  "websites",
  "apps",
  "indie_games",
  "ai_generated_art",
  "ai_music",
  "ai_films",
  "inventions",
  "startup_ideas",
  "architecture",
  "fashion_design",
  "handmade_crafts",
  "experimental_projects",
] as const;

export const platformRoutes = [
  { href: "/explore", label: "Explore" },
  { href: "/trending", label: "Trending" },
  { href: "/ai", label: "AI" },
  { href: "/communities", label: "Communities" },
  { href: "/marketplace", label: "Marketplace" },
] as const;

export const featureMatrix = [
  "Portfolio-grade creator profiles",
  "Personalized and trending discovery",
  "Transparent AI metadata",
  "Communities and collaborative projects",
  "Creator monetization surfaces",
  "Moderation and reporting queues",
] as const;
